-- NOTA: Este script ya no es necesario
-- El sistema de administración usa credenciales hardcoded:
-- Usuario: admin-estacion
-- Contraseña: admin1234
-- 
-- No se requiere insertar ningún usuario en la base de datos para el admin